// Every source the Guide cites. The guide text refers to these by id, e.g. [[mayo-reactive]];
// the numbers readers see are assigned by order of first appearance (see render.js).
//
// Rules for adding one:
//  - Read it first. Each entry below was opened and read on 2026-10-03; `usedFor` says what the
//    guide takes from it, so a reader (or a reviewer) can check the claim against the original.
//  - Prefer the manufacturer, a regulator, a government health service or a peer-reviewed paper.
//  - A source nobody cites fails tests/guide.spec.js, so the list can't drift from the text.
//  - Listing a source is not an endorsement by its authors, and the guide says so.

export const ACCESSED = "3 October 2026";

export const SOURCES = [
  // ---- Reactive hypoglycaemia, diagnosis and definitions ----
  {
    id: "mayo-reactive",
    title: "Reactive hypoglycemia: What causes it?",
    publisher: "Mayo Clinic",
    date: "13 April 2023",
    url: "https://www.mayoclinic.org/diseases-conditions/diabetes/expert-answers/reactive-hypoglycemia/faq-20057778",
    usedFor: "What reactive hypoglycaemia is (low blood sugar within about four hours of a meal), its symptoms, and other possible causes.",
  },
  {
    id: "cleveland-reactive",
    title: "How to Treat Reactive Hypoglycemia",
    publisher: "Cleveland Clinic (reviewed by Julia Zumpano, RD)",
    date: "7 September 2021",
    url: "https://health.clevelandclinic.org/how-to-treat-reactive-hypoglycemia",
    usedFor: "Typical timing after a meal, and that the exact cause is often unknown.",
  },
  {
    id: "nhs-northtees",
    title: "Dietary advice for reactive hypoglycaemia",
    publisher: "North Tees and Hartlepool NHS Foundation Trust",
    date: "page last reviewed 30 March 2026",
    url: "https://www.nth.nhs.uk/resources/reactive-hypoglycaemia/",
    usedFor: "Timing (about two to four hours after a meal), that it often follows stomach surgery, and testing blood glucose when symptoms occur.",
  },
  {
    id: "endo-2009",
    title: "Evaluation and management of adult hypoglycemic disorders: an Endocrine Society Clinical Practice Guideline",
    publisher: "Cryer PE, Axelrod L, Grossman AB, Heller SR, Montori VM, Seaquist ER, Service FJ. J Clin Endocrinol Metab 2009;94:709-728",
    date: "2009",
    url: "https://doi.org/10.1210/jc.2008-1410",
    usedFor: "Whipple's triad: symptoms, a low glucose measured at the time, and relief when glucose is raised.",
  },
  {
    id: "ada-2026-s6",
    title: "6. Glycemic Goals, Hypoglycemia, and Hyperglycemic Crises: Standards of Care in Diabetes-2026",
    publisher: "American Diabetes Association Professional Practice Committee. Diabetes Care 2026;49(Suppl 1):S132-S149",
    date: "2026",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12690178/",
    usedFor: "The three levels of hypoglycaemia and the 3.9 mmol/L (70 mg/dL) alert value, sensor lag, pressure on a sensor during sleep, and hypoglycaemia unawareness.",
  },
  {
    id: "ihsg-2017",
    title: "Glucose concentrations of less than 3.0 mmol/l (54 mg/dl) should be reported in clinical trials: a joint position statement of the American Diabetes Association and the European Association for the Study of Diabetes",
    publisher: "International Hypoglycaemia Study Group. Diabetologia (also Diabetes Care 2017;40:155-157)",
    date: "2016-2017",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6518070/",
    usedFor: "Why 3.0 mmol/L (54 mg/dL) is treated as a clinically significant low, separate from the 3.9 mmol/L alert value.",
  },
  {
    id: "tir-2019",
    title: "Clinical Targets for Continuous Glucose Monitoring Data Interpretation: Recommendations From the International Consensus on Time in Range",
    publisher: "Battelino T, et al. Diabetes Care 2019 (doi:10.2337/dci19-0028)",
    date: "2019",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6973648/",
    usedFor: "The standard time-in-range targets for people with type 1 or type 2 diabetes, and how much sensor data they need.",
  },
  {
    id: "shah-2019",
    title: "Continuous Glucose Monitoring Profiles in Healthy Nondiabetic Participants: A Multicenter Prospective Study",
    publisher: "Shah VN, et al. J Clin Endocrinol Metab 2019;104(10):4356-4364 (doi:10.1210/jc.2018-02763)",
    date: "2019",
    url: "https://doi.org/10.1210/jc.2018-02763",
    usedFor: "How much time people without diabetes spend below 3.9 mmol/L (70 mg/dL) on a sensor, and their typical average glucose.",
  },

  // ---- Low-glucose first aid and diabetes basics (Australia first) ----
  {
    id: "diabetesaus-hypo",
    title: "Hypoglycaemia (hypo) and Hyperglycaemia",
    publisher: "Diabetes Australia",
    date: "undated",
    url: "https://www.diabetesaustralia.com.au/managing-diabetes/hypo-hyperglycaemia/",
    usedFor: "The Australian definition of a low (below 4.0 mmol/L), the first-aid steps and quantities, and what to do if someone is unconscious.",
  },
  {
    id: "healthdirect-hypo",
    title: "Hypoglycaemia (low blood sugar): causes, signs, symptoms and management",
    publisher: "healthdirect Australia",
    date: "last reviewed November 2024",
    url: "https://www.healthdirect.gov.au/hypoglycaemia-low-blood-sugar",
    usedFor: "Symptoms, common causes in people with diabetes, first-aid steps, when to call 000, and seeing a doctor about frequent lows.",
  },
  {
    id: "niddk-hypo",
    title: "Low Blood Glucose (Hypoglycemia)",
    publisher: "National Institute of Diabetes and Digestive and Kidney Diseases (US)",
    date: "last reviewed July 2021",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/low-blood-glucose-hypoglycemia",
    usedFor: "Symptoms, including during sleep, and hypoglycaemia unawareness.",
  },
  {
    id: "niddk-diabetes",
    title: "What Is Diabetes?",
    publisher: "National Institute of Diabetes and Digestive and Kidney Diseases (US)",
    date: "last reviewed April 2023",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/what-is-diabetes",
    usedFor: "Plain definitions of type 1, type 2, gestational diabetes and prediabetes.",
  },
  {
    id: "diabetesaus-types",
    title: "About diabetes",
    publisher: "Diabetes Australia",
    date: "undated",
    url: "https://www.diabetesaustralia.com.au/about-diabetes/",
    usedFor: "The main types of diabetes, from an Australian source.",
  },

  // ---- Food, carbohydrate and portions ----
  {
    id: "evert-2019",
    title: "Nutrition Therapy for Adults With Diabetes or Prediabetes: A Consensus Report",
    publisher: "Evert AB, et al. Diabetes Care 2019;42:731-754 (doi:10.2337/dci19-0014)",
    date: "2019",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7011201/",
    usedFor: "Carbohydrate as the main dietary influence on glucose after meals, monitoring carbohydrate intake, glycaemic index findings, and alcohol and delayed lows.",
  },
  {
    id: "brazeau-2013",
    title: "Carbohydrate counting accuracy and blood glucose variability in adults with type 1 diabetes",
    publisher: "Brazeau AS, et al. Diabetes Res Clin Pract 2013;99:19-23 (doi:10.1016/j.diabres.2012.10.024)",
    date: "2013",
    url: "https://doi.org/10.1016/j.diabres.2012.10.024",
    usedFor: "How far off people's own carbohydrate estimates for meals tend to be.",
  },
  {
    id: "joubert-2021",
    title: "Prospective Independent Evaluation of the Carbohydrate Counting Accuracy of Two Smartphone Applications",
    publisher: "Joubert M, et al. Diabetes Therapy 2021",
    date: "2021",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8266981/",
    usedFor: "Why a photo-based carbohydrate estimate is treated as rough.",
  },
  {
    id: "fsanz-nip",
    title: "Nutrition information panels",
    publisher: "Food Standards Australia New Zealand",
    date: "undated",
    url: "https://www.foodstandards.gov.au/consumer/labelling/panels",
    usedFor: "What an Australian food label shows: carbohydrate and sugars per serving and per 100 g, and that serving size is chosen by the manufacturer.",
  },
  {
    id: "sydney-gi",
    title: "About GI",
    publisher: "Glycemic Index Research Service, University of Sydney",
    date: "undated",
    url: "https://glycemicindex.com/about-gi/",
    usedFor: "What the glycaemic index is and how it is measured.",
  },
  {
    id: "healthdirect-gi",
    title: "Glycaemic index (GI)",
    publisher: "healthdirect Australia",
    date: "last reviewed June 2024",
    url: "https://www.healthdirect.gov.au/glycaemic-index-gi",
    usedFor: "What can lower the glycaemic index of a food or meal (fibre, protein, acid, cooling).",
  },
  {
    id: "off-terms",
    title: "Terms of use",
    publisher: "Open Food Facts",
    date: "undated",
    url: "https://world.openfoodfacts.org/terms-of-use",
    usedFor: "That the barcode database is built by volunteers, may contain errors, and is indicative only; also its licence and the credit it asks for.",
  },

  // ---- Sensors, meters and how they differ ----
  {
    id: "abbott-au-differences",
    title: "Why Blood Glucose Won't Always Match Sensor Glucose",
    publisher: "Abbott, FreeStyle Libre Australia",
    date: "undated",
    url: "https://www.freestylelibre.com.au/difference-between-glucose-interstitial-glucose",
    usedFor: "Why a sensor and a finger-prick differ, the 5 to 10 minute delay, and when to use a finger-prick.",
  },
  {
    id: "abbott-au-faq",
    title: "Frequently Asked Questions",
    publisher: "Abbott, FreeStyle Libre Australia",
    date: "undated",
    url: "https://www.freestylelibre.com.au/faq",
    usedFor: "The one-hour warm-up, and that LibreLinkUp sharing is not intended for treatment decisions.",
  },
  {
    id: "abbott-qrg",
    title: "Flash Glucose Monitoring System Quick Reference Guide: FreeStyle Libre 2 and FreeStyle Libre 2 Plus (Important User Information, US edition)",
    publisher: "Abbott Diabetes Care",
    date: "2023",
    url: "https://freestyleserver.com/Payloads/IFU/2023/q3/ART44507-601_rev-A-web.pdf",
    usedFor: "Libre 2 Plus wear time, where and how to apply it, sites to avoid, storage, vitamin C, loose sensors, and when to check with a finger-prick.",
  },
  {
    id: "abbott-substances",
    title: "Substances That May Affect FreeStyle Libre 2 Plus Sensor Accuracy",
    publisher: "Abbott (international site)",
    date: "undated",
    url: "https://www.freestyle.abbott/en-om/support/what-substances-could-interfere-with-the-results-generated-by-the-freestyle-libre-2-plus-system-1.html",
    usedFor: "That vitamin C can falsely raise Libre 2 Plus readings and aspirin can slightly lower them.",
  },
  {
    id: "libre2-men",
    title: "Analytical Performance of the FreeStyle Libre 2 Glucose Sensor in Healthy Male Adults",
    publisher: "Fellinger E, et al. Sensors (Basel) 2024",
    date: "2024",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11397946/",
    usedFor: "A published accuracy figure for the Libre 2 in 44 healthy men (average difference 12.9%).",
  },
  {
    id: "libre2-women",
    title: "Analytical Performance of the Factory-Calibrated Flash Glucose Monitoring System FreeStyle Libre2 in Healthy Women",
    publisher: "Jin Z, et al. Sensors (Basel) 2023",
    date: "2023",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10490447/",
    usedFor: "A published accuracy figure for the Libre 2 in 29 healthy women, including the low range.",
  },
  {
    id: "dexcom-au-sites",
    title: "Where do I insert my Dexcom ONE+ sensor",
    publisher: "Dexcom Australia",
    date: "undated",
    url: "https://www.dexcom.com/en-au/faqs/where-do-i-insert-my-dexcom-one-plus-sensor",
    usedFor: "Approved Dexcom ONE+ sites by age.",
  },
  {
    id: "dexcom-insert",
    title: "How to Insert Dexcom Sensors",
    publisher: "Dexcom (UK site)",
    date: "undated",
    url: "https://www.dexcom.com/en-GB/faqs/sensor-insertion",
    usedFor: "Choosing and rotating a site, what to avoid, and keeping clear of an insulin pump or injection site.",
  },
  {
    id: "dexcom-au-mismatch",
    title: "What should I do if my sensor reading and blood glucose value don't match?",
    publisher: "Dexcom Australia",
    date: "undated",
    url: "https://www.dexcom.com/en-au/faqs/what-should-i-do-if-my-sensor-reading-and-blood-glucose-value-dont-match",
    usedFor: "Dexcom's tolerance between sensor and meter, the reasons they differ, and which number to use.",
  },
  {
    id: "dexcom-au-bgvscgm",
    title: "BG meter vs. CGM reading",
    publisher: "Dexcom Australia",
    date: "undated",
    url: "https://www.dexcom.com/en-au/faqs/bg-meter-vs-cgm-reading",
    usedFor: "Blood glucose moving before interstitial glucose, new-sensor differences, lying on a sensor, and clean hands for finger-pricks.",
  },
  {
    id: "dexcom-au-calibrate",
    title: "Can Dexcom sensors be calibrated?",
    publisher: "Dexcom Australia",
    date: "undated",
    url: "https://www.dexcom.com/en-au/faqs/can-dexcom-sensors-be-calibrated",
    usedFor: "That calibration is optional, when not to do it, and how to do it correctly.",
  },
  {
    id: "dexcom-au-launch",
    title: "Dexcom ONE+ launches in Australia to offer innovative continuous glucose monitoring for Aussies living with type 2 diabetes",
    publisher: "Dexcom Australia",
    date: "undated",
    url: "https://www.dexcom.com/en-AU/news/dexcom-oneplus-launches-in-australia",
    usedFor: "Dexcom ONE+ wear time (10 days plus a 12-hour grace period) and its 30-minute warm-up.",
  },
  {
    id: "dexcom-setup",
    title: "How do I set up my Dexcom ONE+ system?",
    publisher: "Dexcom (UK site)",
    date: "undated",
    url: "https://www.dexcom.com/en-GB/faqs/how-do-i-set-up-my-dexcom-one-plus-system",
    usedFor: "Pairing with the applicator code, and a reading every 5 minutes.",
  },
  {
    id: "dexcom-compat",
    title: "Is my smartphone compatible with the Dexcom ONE+ app?",
    publisher: "Dexcom Australia",
    date: "undated",
    url: "https://www.dexcom.com/en-au/faqs/is-my-smartphone-compatible-with-the-dexcom-one-plus-app",
    usedFor: "Checking Dexcom's compatibility chart before updating the phone's operating system.",
  },
  {
    id: "dexcom-api-delay",
    title: "Endpoint Overview (Dexcom API)",
    publisher: "Dexcom Developer",
    date: "undated",
    url: "https://developer.dexcom.com/docs/dexcomv3/endpoint-overview",
    usedFor: "Why Dexcom readings reach other apps up to three hours late outside the United States.",
  },
  {
    id: "roche-guideme",
    title: "Accu-Chek Guide Me Blood Glucose Meter: User's Manual (US edition)",
    publisher: "Roche Diabetes Care",
    date: "2023",
    url: "https://www.accu-chek.com/document/accu-chek-guide-me-users-manual-english/download",
    usedFor: "How to test, strips and control solution, alternative-site limits, pairing over Bluetooth, and not sharing the meter.",
  },

  // ---- The web platform this app runs on, and the rules around it ----
  {
    id: "mdn-bcd-bluetooth",
    title: "Browser compatibility data for the Bluetooth API (api/Bluetooth.json)",
    publisher: "MDN browser-compat-data (Mozilla)",
    date: "undated",
    url: "https://github.com/mdn/browser-compat-data/blob/main/api/Bluetooth.json",
    usedFor: "Which browsers support Web Bluetooth: Chrome, Edge, Opera and Samsung Internet do; Firefox and Safari, including on iPhone, do not.",
  },
  {
    id: "mdn-bluetooth",
    title: "Web Bluetooth API",
    publisher: "MDN Web Docs (Mozilla)",
    date: "undated",
    url: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API",
    usedFor: "What Web Bluetooth is, that it needs a secure page and a tap, and that it is not available in every browser.",
  },
  {
    id: "webkit-itp",
    title: "Full Third-Party Cookie Blocking and More",
    publisher: "John Wilander, WebKit blog",
    date: "24 March 2020",
    url: "https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/",
    usedFor: "Safari deleting a website's stored data after seven days without use, and home-screen apps being exempt.",
  },
  {
    id: "mdn-storage",
    title: "Storage quotas and eviction criteria",
    publisher: "MDN Web Docs (Mozilla)",
    date: "undated",
    url: "https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria",
    usedFor: "When a browser may clear a site's stored data, and that it is all-or-nothing.",
  },
  {
    id: "tga-exclusions",
    title: "Software-based medical device exclusions",
    publisher: "Therapeutic Goods Administration (Australia)",
    date: "last updated 16 March 2026",
    url: "https://www.tga.gov.au/products/medical-devices/software-and-artificial-intelligence-ai/overview/software-based-medical-device-exclusions",
    usedFor: "That software counting as a medical device is regulated unless a listed exclusion applies, and every function must fit.",
  },
];
